name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout Repository
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------------
      # Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ----------------------------
      # Install Dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ----------------------------
      # Run Unit Tests
      # ----------------------------
      - name: Run unit tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest

      # ---------------------------
      # Debug docker log
      # ---------------------------
      # - name: Debug Docker Username
      #   run: echo "Docker username is: ${{ secrets.DOCKER_USERNAME }}"
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u BhavnaYa --password-stdin


      # ----------------------------
      # Build Docker Image
      # ----------------------------
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cats-dogs:latest .

      # ----------------------------
      # Login to DockerHub
      # ----------------------------
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ----------------------------
      # Push Docker Image
      # ----------------------------
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cats-dogs:latest

      # ----------------------------
      # Run Container for Smoke Test
      # ----------------------------
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/cats-dogs:latest
          sleep 15

      # ----------------------------
      # Smoke Test
      # ----------------------------
      - name: Run smoke test
        run: python smoke_test.py
